### ISSUE TITLE
Please add usage instructions

### ISSUE THREAD

**Issue by unixorn** [perlpunk/MooseX-App-Plugin-ZshCompletion#3]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I don't really understand how to use it and suspect other non-perl folks will have similar issues. Please add some usage instructions, thanks.

**Comment by perlpunk** [comment]
Thanks!
I think this might not be a good candidate for your zsh plugin site, though.
It's a plugin for the MooseX::App perl module, which is a command line framework. MooseX::App itself comes with a bash completion generator, and I just added this plugin for zsh.
So it's only useful for people writing perl command line tools with MooseX::App.

I should add a README though to make this clear, I guess.

However, maybe this the following is interesting:
https://github.com/perlpunk/shell-completions
These completion scripts are automatically generated from YAML specifications.
While writing a good completion (for bash or zsh) might be difficult, writing such a spec is easy.
For example look at the one for `jq`: https://github.com/perlpunk/shell-completions/blob/master/specs/jq.yaml

It also supports calling external commands for completion, for example the one for `mpath` (which takes a perl module name as a parameter):
https://github.com/perlpunk/shell-completions/blob/master/specs/mpath.yaml

The tool for generating the completions can be found here:
https://github.com/perlpunk/App-AppSpec-p5
If this sounds interesting, I will try and add some instructions on how to install and use it for non perl folks.

Thanks!

**Comment by unixorn** [comment]
That sounds like a super helpful tool especially since it supports `bash` too. Thanks for wrapping it in a ZSH plugin. Let me know when you've made the README and I'll add it to the plugin list.

**Comment by perlpunk** [comment]
I made a PR https://github.com/unixorn/awesome-zsh-plugins/pull/705

**Comment by unixorn** [comment]
Thanks for adding the instructions and thanks for the PR
